# Generated by Django 5.1.1 on 2024-10-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.FileField(upload_to='test/file')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updatde_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='profile/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('reel', 'Reel'), ('post', 'Post'), ('carousel', 'Carousel')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
