# Generated by Django 5.1.6 on 2025-03-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_testpost_rename_updatde_at_post_updated_at_post_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('reel', 'Reel'), ('post', 'Post'), ('carousel', 'Carousel')], default='post', max_length=10),
        ),
    ]
