# Generated by Django 5.1.6 on 2025-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('account_locked', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('show_birthday', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['username', 'email'], name='user_user_usernam_d9f59e_idx')],
            },
        ),
    ]
